apiVersion: v2
name: skeleton-app
description: "Skeleton Helm chart for a simple web app (Deployment + Service + Ingress)"
type: application
version: 0.1.0        # versión del chart (semver)
appVersion: "1.0.0"   # versión de la app (informativo)
kubeVersion: ">=1.24.0-0"
keywords:
  - skeleton
  - web
home: https://github.com/mariano-tp/helm-chart-skeleton
sources:
  - https://github.com/mariano-tp/helm-chart-skeleton
maintainers:
  - name: mariano-tp
    url: https://github.com/mariano-tp
