name: chart-ci
on:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'
      - '.github/workflows/chart-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'charts/**'
  workflow_dispatch:

concurrency:
  group: chart-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Helm lint
        run: helm lint charts/skeleton-app

      - name: Render templates
        run: |
          helm template demo charts/skeleton-app \
            --namespace demo --create-namespace > rendered.yaml

      - name: Upload rendered manifests
        uses: actions/upload-artifact@v4
        with:
          name: rendered-manifests
          path: rendered.yaml
