name: chart-release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Package chart
        run: |
          helm package charts/skeleton-app --destination dist
          ls -lh dist

      - name: Upload .tgz to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
