name: chart-ci

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'
      - '.github/workflows/chart-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  lint-and-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Helm lint
        run: |
          set -euo pipefail
          helm lint charts/skeleton-app

      - name: Render templates
        run: |
          mkdir -p rendered
          helm template demo charts/skeleton-app \
            --values charts/skeleton-app/values.yaml \
            > rendered/all.yaml

      - name: Upload rendered manifests
        uses: actions/upload-artifact@v4
        with:
          name: rendered-manifests
          path: rendered/all.yaml
