name: chart-ci

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  lint-and-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2

      - name: Helm lint
        run: helm lint charts/skeleton-app

      - name: Render templates
        run: |
          helm template demo charts/skeleton-app \
            --values charts/skeleton-app/values.yaml > rendered.yaml

      - name: Upload rendered manifests
        uses: actions/upload-artifact@v4
        with:
          name: rendered-manifests
          path: rendered.yaml

  install-test:
    runs-on: ubuntu-latest
    needs: lint-and-template
    steps:
      - uses: actions/checkout@v4

      - name: Create kind cluster
        uses: helm/kind-action@v1
        with:
          version: v0.23.0
          node_image: kindest/node:v1.28.9

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2

      - name: Install chart into kind
        run: |
          kubectl cluster-info
          helm install demo charts/skeleton-app --wait --timeout 120s
          kubectl rollout status deploy/demo --timeout=120s
          kubectl get all -l app.kubernetes.io/instance=demo -o wide
