name: chart-ci

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  lint-and-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Helm lint
        run: |
          helm lint charts/skeleton-app

      - name: Render templates (helm template)
        run: |
          helm template demo charts/skeleton-app --debug
